permalink: "/blog/:year/:month/:day/:title"
tusd_endpoint: "http://master.tus.io"
markdown: redcarpet
rss_feed: http://feeds.feedburner.com/tusio
navigation:
- text: Home
  url: /index.html
- text: About
  url: /about.html
- text: Blog
  url: /blog.html
- text: Demo
  url: /demo.html
- text: Protocol
  url: /protocols/resumable-upload.html
- text: Implementations
  url: /implementations.html

authors:
  felixge:
    name: Felix Geisendörfer
    gravatar: 23968f0ca75b13463d2db5343e5c2096
    email: felix@transloadit.com
    web: http://felixge.de
    twitter: felixge
    github: felixge
  tim_kos:
    name: Tim Koschützki
    gravatar: 9c31d1102d95104fb994ae67cd1989b6
    email: tim@transloadit.com
    web: http://debuggable.com
    twitter: tim_kos
    github: tim-kos
  kvz:
    name: Kevin van Zonneveld
    gravatar: 3210e1be3e4059b93c4a88309e2183a2
    email: kevin@transloadit.com
    web: http://kvz.io
    twitter: kvz
    github: kvz
  vayam:
    name: Naren Venkataraman
    gravatar: 3b5a456c814b3235a7f0bffa27406022
    email: naren@doorul.com
    web: http://dev.doorul.com
    twitter: asyncme
    github: vayam

