permalink: "/blog/:year/:month/:day/:title"
markdown: redcarpet
navigation:
- text: Home
  url: /index.html
- text: About
  url: /about.html
- text: Blog
  url: /blog.html
- text: Protocol
  url: /docs/http-protocol.html
- text: Demo
  url: /demo.html
- text: FAQ
  url: /faq.html
