permalink: "/blog/:year/:month/:day/:title"
tusd_endpoint: "http://master.tus.io"

kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6

rss_feed: http://feeds.feedburner.com/tusio
url: http://tus.io

navigation:
- text: Home
  url: /
- text: About
  url: /about.html
- text: Blog
  url: /blog.html
- text: Shop
  url: http://shop.tus.io/collections/all
- text: Demo
  url: /demo.html
- text: Protocol
  url: /protocols/resumable-upload.html
- text: Implementations
  url: /implementations.html

authors:
  felixge:
    name: Felix Geisendörfer
    gravatar: 23968f0ca75b13463d2db5343e5c2096
    email: felix@transloadit.com
    web: http://felixge.de
    twitter: felixge
    github: felixge
  tim_kos:
    name: Tim Koschützki
    gravatar: 9c31d1102d95104fb994ae67cd1989b6
    email: tim@transloadit.com
    web: http://debuggable.com
    twitter: tim_kos
    github: tim-kos
  kvz:
    name: Kevin van Zonneveld
    gravatar: 3210e1be3e4059b93c4a88309e2183a2
    email: kevin@transloadit.com
    web: http://kvz.io
    twitter: kvz
    github: kvz
  vayam:
    name: Naren Venkataraman
    gravatar: 3b5a456c814b3235a7f0bffa27406022
    email: naren@doorul.com
    web: http://dev.doorul.com
    twitter: asyncme
    github: vayam
  acconut:
    name: Marius Kleidl
    gravatar: cda1e4d36e22cbcd826f0f09f8c19f04
    email: marius@transloadit.com
    twitter: acconut_
    github: Acconut

implementations:
- name: tus-js-client
  icon: prog-js01
- name: tus-java-client
  icon: prog-java
- name: tus-android-client
  icon: android
- name: TUSKit
  icon: os-ios
- name: tusd
  icon: prog-golang02
