permalink: "/blog/:year/:month/:day/:title"
markdown: redcarpet
rss_feed: http://tus.io/atom.xml
navigation:
- text: Home
  url: /index.html
- text: Blog
  url: /blog.html
- text: Demo
  url: /demo.html
