permalink: "/blog/:year/:month/:day/:title"
tusd_endpoint: "http://master.tus.io"

kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6

# We'll refer new atom feed though, as adviced by GitHub
# https://github.com/blog/2053-easier-feeds-for-github-pages
feed:
  path: blog.atom

url: http://tus.io

gems:
  - jemoji
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-redirect-from

emoji:
  src: "/assets/img"

assets:
  debug         : false
  cachebust     : hard
  gzip          : [ text/css, application/javascript ]
  cache         : true
  js_compressor : uglifier
  css_compressor: false
  sources       :
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors
    - node_modules

browsers:
  - "last 1 version"
  - "> 1%"
  - "Explorer 10"

exclude: [vendor]

navigation:
- text: Home
  url: /
- text: About
  url: /about.html
- text: Blog
  url: /blog.html
- text: Shop
  url: http://shop.tus.io/collections/all
- text: Demo
  url: /demo.html
- text: Protocol
  url: /protocols/resumable-upload.html
- text: Implementations
  url: /implementations.html

authors:
  felixge:
    name: Felix Geisendörfer
    gravatar: 23968f0ca75b13463d2db5343e5c2096
    email: felix@transloadit.com
    web: http://felixge.de
    twitter: felixge
    github: felixge
  tim_kos:
    name: Tim Koschützki
    gravatar: 9c31d1102d95104fb994ae67cd1989b6
    email: tim@transloadit.com
    web: http://debuggable.com
    twitter: tim_kos
    github: tim-kos
  kvz:
    name: Kevin van Zonneveld
    gravatar: 3210e1be3e4059b93c4a88309e2183a2
    email: kevin@transloadit.com
    web: http://kvz.io
    twitter: kvz
    github: kvz
  vayam:
    name: Naren Venkataraman
    gravatar: 3b5a456c814b3235a7f0bffa27406022
    email: naren@doorul.com
    web: http://dev.doorul.com
    twitter: asyncme
    github: vayam
  acconut:
    name: Marius Kleidl
    gravatar: cda1e4d36e22cbcd826f0f09f8c19f04
    email: marius@transloadit.com
    twitter: acconut_
    github: Acconut

implementations:
- name: tus-js-client
  icon: prog-js01
- name: tus-java-client
  icon: prog-java
- name: tus-android-client
  icon: android
- name: TUSKit
  icon: os-ios
- name: tusd
  icon: prog-golang02

features:
- title: HTTP-based
  content: |
    Built as a layer on top of the popular HTTP protocol, tus can easily be integrated
    into applications using existing libraries, proxies and firewalls, and can
    be used directly from any website.
- title: Production-ready
  content: |
    tus is ready for use in production. It has undergone numerous
    rounds of improvements and received valuable feedback from people working at Vimeo, Google
    and multiple other well-known companies.
- title: Open source
  content: |
    The source code to all of our implementations, this website and even the protocol
    itself is accessible to everyone under MIT license, directly from our
    [GitHub](https://github.com/tus) organization.
- title: Minimalistic design...
  content: |
    The specification only requires a very small set of features to be
    implemented by clients and servers. tus embraces simplicity, fast
    development and iteration speed for everyone.
- title: ... yet still extensible
  content: |
    tus nevertheless features a sizable list of extensions that introduce additional
    functionality, such as parallel uploading or checksums and expiration. All of these may be 
    implemented according to your preferences.
- title: Community-owned
  content: |
    We believe in an open and accessible evolution of this protocol. At any
    stage since the beginning of tus, feedback has been appreciated and
    integrated. We look forward to your contributions as well.
