permalink: "/blog/:year/:month/:day/:title"
markdown: redcarpet
rss_feed: http://tus.io/atom.xml
navigation:
- text: Home
  url: /index.html
- text: Blog
  url: /blog.html
- text: Demo
  url: /demo.html
- text: Protocol
  url: https://github.com/tus/tus-resumable-upload-protocol/blob/master/README.md
- text: Implementations
  url: /implementations.html

authors:
  felixge:
    name: Felix Geisendörfer
    gravatar: 23968f0ca75b13463d2db5343e5c2096
    email: felix@transloadit.com
    web: http://felixge.de
    twitter: felixge
    github: felixge
  tim_kos:
    name: Tim Koschützki
    gravatar: 9c31d1102d95104fb994ae67cd1989b6
    email: tim@transloadit.com
    web: http://debuggable.com
    twitter: tim_kos
    github: tim-kos
  kvz:
    name: Kevin van Zonneveld
    gravatar: 3210e1be3e4059b93c4a88309e2183a2
    email: kevin@transloadit.com
    web: http://kvz.io
    twitter: kvz
    github: kvz