permalink: "/blog/:year/:month/:day/:title"
markdown: redcarpet
rss_feed: http://tus.io/atom.xml
navigation:
- text: Home
  url: /index.html
- text: Blog
  url: /blog.html
- text: Demo
  url: /demo.html

authors:
  felixge:
    name: Felix Geisendörfer
    gravatar: 3933b38a349355d514fb4659457ef1d9
    email: felix@transloadit.com
    web: http://felixge.de
    twitter: felixge
    github: felixge
  tim_kos:
    name: Tim Koschützki
    gravatar: 1912af33a9771e5d24ab8d402864fb58
    email: tim@transloadit.com
    web: http://debuggable.com
    twitter: tim_kos
    github: tim-kos
  kvz:
    name: Kevin van Zonneveld
    gravatar: 16369618649852f72876a1d9eb3cb4cc
    email: kevin@transloadit.com
    web: http://kvz.io
    twitter: kvz
    github: kvz