permalink: "/blog/:year/:month/:day/:title"
tusd_endpoint: "http://master.tus.io"

kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6

# We'll refer new atom feed though, as adviced by GitHub
# https://github.com/blog/2053-easier-feeds-for-github-pages
feed:
  path: blog.atom

rss_feed: /atom.xml

url: http://tus.io

gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

emoji:
  src: "/assets/img"

browsers:
  - "last 1 version"
  - "> 1%"
  - "Explorer 10"

exclude: [vendor]
